In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
textfiledata = "20122014.txt"
datapanda = pd.read_csv(textfiledata,delim_whitespace=True,header=None)

In [40]:
print(datapanda)

          0    1   2     3    4         5     6      7   8
0      2012    1   0   4.0  0.8   39645.0   7.2  379.0  -8
1      2012    1   1   4.4 -1.9   47667.0   7.8  386.0  -3
2      2012    1   2   4.8  0.1   53575.0   7.0  380.0  -4
3      2012    1   3   5.4 -2.4   55962.0   7.6  374.0  -5
4      2012    1   4   4.5 -1.8   55105.0   7.2  369.0  -9
5      2012    1   5   4.2  0.1   51599.0   6.8  368.0  -7
6      2012    1   6   4.7 -0.9   51124.0   6.6  367.0  -6
7      2012    1   7   4.1 -2.0   51021.0   7.4  361.0 -10
8      2012    1   8   3.2 -0.1   54233.0   7.6  362.0  -7
9      2012    1   9   4.3  1.9   43424.0   7.7  367.0  -3
10     2012    1  10   4.5  0.5   46735.0   6.0  365.0  -6
11     2012    1  11   5.6 -2.4   40214.0   4.8  369.0  -8
12     2012    1  12   5.2 -2.3   46852.0   5.4  366.0  -8
13     2012    1  13   4.4 -2.0   59994.0   6.1  370.0  -7
14     2012    1  14   4.8 -2.4   56908.0   5.9  357.0  -5
15     2012    1  15   4.6 -2.1   57530.0   5.6  354.0  

In [41]:
dens = datapanda.loc[1:,3].values

for i in range(0, len(dens)):
    if dens[i] == 999.9:
        j = 1
        while dens[i+j] == 999.9:
            j = j+1
        diff = (dens[i+j] - dens[i-1])/ (j+1)
        for h in range(1, j+1):
            dens[i+h-1] = dens[i-1] + h *diff
            
datapanda.loc[1:,3] = dens


In [42]:
dens = datapanda.loc[1:,4].values

for i in range(0, len(dens)):
    if dens[i] == 999.9:
        j = 1
        while dens[i+j] == 999.9:
            j = j+1
        diff = (dens[i+j] - dens[i-1])/ (j+1)
        for h in range(1, j+1):
            dens[i+h-1] = dens[i-1] + h *diff
            
datapanda.loc[1:,4] = dens


In [43]:
dens = datapanda.loc[1:,5].values

for i in range(0, len(dens)):
    if dens[i] == 9999999.:
        j = 1
        while dens[i+j] == 9999999.:
            j = j+1
        diff = (dens[i+j] - dens[i-1])/ (j+1)
        for h in range(1, j+1):
            dens[i+h-1] = dens[i-1] + h *diff
            
datapanda.loc[1:,5] = dens


In [44]:
dens = datapanda.loc[1:,6].values

for i in range(0, len(dens)):
    if dens[i] == 999.9:
        j = 1
        while dens[i+j] == 999.9:
            j = j+1
        diff = (dens[i+j] - dens[i-1])/ (j+1)
        for h in range(1, j+1):
            dens[i+h-1] = dens[i-1] + h *diff
            
datapanda.loc[1:,6] = dens

In [45]:
speed = datapanda.loc[1:,7].values

for i in range(0, len(speed)):
    if speed[i] == 9999.:
        j = 1
        while speed[i+j] == 9999.:
            j = j+1
        diff = (speed[i+j] - speed[i-1])/ (j+1)
        for h in range(1, j+1):
            speed[i+h-1] = speed[i-1] + h *diff
            
datapanda.loc[1:,7] = speed

In [46]:
print(datapanda)

          0    1   2     3    4         5     6      7   8
0      2012    1   0   4.0  0.8   39645.0   7.2  379.0  -8
1      2012    1   1   4.4 -1.9   47667.0   7.8  386.0  -3
2      2012    1   2   4.8  0.1   53575.0   7.0  380.0  -4
3      2012    1   3   5.4 -2.4   55962.0   7.6  374.0  -5
4      2012    1   4   4.5 -1.8   55105.0   7.2  369.0  -9
5      2012    1   5   4.2  0.1   51599.0   6.8  368.0  -7
6      2012    1   6   4.7 -0.9   51124.0   6.6  367.0  -6
7      2012    1   7   4.1 -2.0   51021.0   7.4  361.0 -10
8      2012    1   8   3.2 -0.1   54233.0   7.6  362.0  -7
9      2012    1   9   4.3  1.9   43424.0   7.7  367.0  -3
10     2012    1  10   4.5  0.5   46735.0   6.0  365.0  -6
11     2012    1  11   5.6 -2.4   40214.0   4.8  369.0  -8
12     2012    1  12   5.2 -2.3   46852.0   5.4  366.0  -8
13     2012    1  13   4.4 -2.0   59994.0   6.1  370.0  -7
14     2012    1  14   4.8 -2.4   56908.0   5.9  357.0  -5
15     2012    1  15   4.6 -2.1   57530.0   5.6  354.0  

In [47]:
print(datapanda.values)

[[ 2.012e+03  1.000e+00  0.000e+00 ...  7.200e+00  3.790e+02 -8.000e+00]
 [ 2.012e+03  1.000e+00  1.000e+00 ...  7.800e+00  3.860e+02 -3.000e+00]
 [ 2.012e+03  1.000e+00  2.000e+00 ...  7.000e+00  3.800e+02 -4.000e+00]
 ...
 [ 2.014e+03  1.000e+00  2.100e+01 ...  5.100e+00  5.320e+02 -2.500e+01]
 [ 2.014e+03  1.000e+00  2.200e+01 ...  5.200e+00  5.430e+02 -1.700e+01]
 [ 2.014e+03  1.000e+00  2.300e+01 ...  5.800e+00  5.580e+02 -1.300e+01]]


In [48]:
#np.savetxt(r'datashizzle.txt', datapanda.values, fmt='%d')

In [49]:
datapanda.to_pickle('20122014.pkl')

In [50]:
df = pd.read_pickle('20122014.pkl')

print(df)

          0    1   2     3    4         5     6      7   8
0      2012    1   0   4.0  0.8   39645.0   7.2  379.0  -8
1      2012    1   1   4.4 -1.9   47667.0   7.8  386.0  -3
2      2012    1   2   4.8  0.1   53575.0   7.0  380.0  -4
3      2012    1   3   5.4 -2.4   55962.0   7.6  374.0  -5
4      2012    1   4   4.5 -1.8   55105.0   7.2  369.0  -9
5      2012    1   5   4.2  0.1   51599.0   6.8  368.0  -7
6      2012    1   6   4.7 -0.9   51124.0   6.6  367.0  -6
7      2012    1   7   4.1 -2.0   51021.0   7.4  361.0 -10
8      2012    1   8   3.2 -0.1   54233.0   7.6  362.0  -7
9      2012    1   9   4.3  1.9   43424.0   7.7  367.0  -3
10     2012    1  10   4.5  0.5   46735.0   6.0  365.0  -6
11     2012    1  11   5.6 -2.4   40214.0   4.8  369.0  -8
12     2012    1  12   5.2 -2.3   46852.0   5.4  366.0  -8
13     2012    1  13   4.4 -2.0   59994.0   6.1  370.0  -7
14     2012    1  14   4.8 -2.4   56908.0   5.9  357.0  -5
15     2012    1  15   4.6 -2.1   57530.0   5.6  354.0  